version: "3"

networks:
  Internal:
    name: LAN
    ipam:
      driver: default
      config:
        - subnet: "10.10.10.0/24"
          gateway: 10.10.10.1

  External:
    name: WAN
    external: true
    driver: bridge

services:
  Grafana:
    image: investment/grafana
    build:
      context: ./Grafana
      dockerfile: Grafana.Dockerfile
    depends_on:
      - PostgreSQL
    container_name: ${GRAFANA_CONTAINER_NAME}
    hostname: ${GRAFANA_HOSTNAME}
    restart: no
    volumes:
      - ./Grafana/datasources:/etc/grafana/provisioning/datasources
      - ./Grafana/dashboards_provisioning:/etc/grafana/provisioning/dashboards
      - ./Grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - ${GRAFANA_EXTERNAL_PORT}:3000
    networks:
      Internal:
        ipv4_address: ${GRAFANA_INTERNAL_IP}
      External: null
    healthcheck:
      test: wget --quiet --tries=1 --output-document=- http://${GRAFANA_HOSTNAME}:3000/api/health
      start_period: 2s
      interval: 3s
      timeout: 1s
      retries: 5

  Flask:
    image: investment/flask
    build:
      context: ./Flask
      dockerfile: Flask.Dockerfile
    depends_on:
      PostgreSQL:
        condition: service_healthy
      Loki:
        condition: service_healthy
    container_name: ${FLASK_CONTAINER_NAME}
    hostname: ${FLASK_HOSTNAME}
    environment:
      DB_IP_Address: ${POSTGRESQL_INTERNAL_IP}
      DB_Username: ${FLASK_DB_USERNAME}
      DB_Password: ${FLASK_DB_PASSWORD}
    restart: unless-stopped
    ports:
      - ${FLASK_EXTERNAL_PORT}:5000
    networks:
      Internal:
        ipv4_address: ${FLASK_INTERNAL_IP}
      External: null
    healthcheck:
      test: curl --fail http://${FLASK_HOSTNAME}:5000/health
      start_period: 2s
      interval: 2s
      timeout: 1s
      retries: 10

  PostgreSQL:
    image: investment/postgresql
    build:
      context: ./PostgreSQL
      dockerfile: PostgreSQL.Dockerfile
    depends_on:
      Loki:
        condition: service_healthy
    container_name: ${POSTGRESQL_CONTAINER_NAME}
    hostname: ${POSTGRESQL_HOSTNAME}
    restart: no
    volumes:
      - ./${POSTGRESQL_PERSISTENT_STORAGE_PATH}:/var/lib/postgresql/data
    ports:
      - ${POSTGRESQL_EXTERNAL_PORT}:5432
    networks:
      Internal:
        ipv4_address: ${POSTGRESQL_INTERNAL_IP}
      External: null
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      start_period: 2s
      interval: 2s
      timeout: 5s
      retries: 10

  Checker:
    image: investment/checker
    build:
      context: ./Checker
      dockerfile: Checker.Dockerfile
    depends_on:
      PostgreSQL:
        condition: service_healthy
      Loki:
        condition: service_healthy
      Flask:
        condition: service_healthy
      DataImporter:
        condition: service_completed_successfully
    container_name: ${CHECKER_CONTAINER_NAME}
    hostname: ${CHECKER_HOSTNAME}
    restart: unless-stopped
    networks:
      Internal:
        ipv4_address: ${CHECKER_INTERNAL_IP}

  DataImporter:
    image: investment/dataimporter
    build:
      context: ./DataImporter
      dockerfile: DataImporter.Dockerfile
    depends_on:
      PostgreSQL:
        condition: service_healthy
      Loki:
        condition: service_healthy
      Flask:
        condition: service_healthy
    container_name: ${DATA_IMPORTER_CONTAINER_NAME}
    hostname: ${DATA_IMPORTER_HOSTNAME}
    restart: no
    networks:
      Internal:
        ipv4_address: ${DATA_IMPORTER_INTERNAL_IP}

  Loki:
    image: grafana/loki:2.9.0
    hostname: ${LOKI_HOSTNAME}
    container_name: ${LOKI_CONTAINER_NAME}
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "${LOKI_EXTERNAL_PORT}:3100"
    networks:
      Internal:
        ipv4_address: ${LOKI_INTERNAL_IP}
      External: null
    healthcheck:
      test: wget --quiet --tries=1 --output-document=- http://${LOKI_HOSTNAME}:3100/ready | grep -q -w ready || exit 1
      start_period: 2s
      interval: 2s
      timeout: 1s
      retries: 10
