FROM grafana/grafana-enterprise


ENV GF_DEFAULT_INSTANCE_NAME="Grafana"
ENV GF_INSTALL_PLUGINS="grafana-clock-panel, grafana-simple-json-datasource, speakyourcode-button-panel, volkovlabs-form-panel"

EXPOSE 3000
