version: "3"
services:
  grafana:
      build:
        context: .
        dockerfile: Dockerfile
      entrypoint:
        - /run.sh
        - /usr/share/grafana/bin/grafana-server
        - --homepath=/usr/share/grafana
        - --config=/etc/grafana-config/grafana.ini
      volumes:
        - ./config:/etc/grafana-config
        - ./datasources:/etc/grafana/provisioning/datasources
        - ./dashboards_provisioning:/etc/grafana/provisioning/dashboards
        - ./dashboards:/var/lib/grafana/dashboards
      ports:
        - "4000:3000"