{
 "title": "Investment Wallet",
 "time": { "from": "now-30d", "to": "now-1d" },
 "templating": {
  "list": [
   {
    "name": "Investment_Owner",
    "label": "Owner",
    "query": "SELECT DISTINCT INVESTMENT_OWNER from INVESTMENTS I ;"
   }
  ]
 },
 "panels": [
  {
   "title": "Investment Profit for Today",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "PLN" } },
   "targets": [
    {
     "rawSql": "WITH results_with_rank AS (\n    SELECT\n        *,\n        ROW_NUMBER () OVER (PARTITION BY fund_id, investment_id ORDER BY result_date DESC) as \"rank\"\n    FROM investment_results\n\n),\n\nfiltered_investment_results AS (\n\tSELECT \n\t\t*\n\tfrom results_with_rank\n\tWHERE  rank = 1\n),\n\nrefund_per_investment AS (\n    SELECT\n        i.investment_name  AS \"Investment name\",\n        SUM(FUND_VALUE - FUND_INVESTED_MONEY) AS \"Profit\"\n    FROM filtered_investment_results ir\n    INNER JOIN (\n        SELECT DISTINCT \n            investment_id, \n            investment_name  \n        FROM investments i\n        WHERE investment_owner = ${Investment_Owner:singlequote}\n    ) i ON i.investment_id  = ir.investment_id\n    GROUP BY i.INVESTMENT_NAME\n)\n\nSELECT \n*,\n(\"Profit\" / (\n    SELECT \n        SUM(\"Profit\")\n    FROM refund_per_investment\n    )\n) * 100 AS \"Profit percentage\"\nFROM refund_per_investment"
    }
   ]
  },
  {
   "title": "Invested Money (investment wallet)",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 5, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    INVESTMENT_NAME,\n    SUM(OPERATION_VALUE)\nFROM INVESTMENTS I\nWHERE investment_owner = ${Investment_Owner:singlequote}\nGROUP BY INVESTMENT_NAME;"
    }
   ]
  },
  {
   "title": "Invested Money (Fund)",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 5, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n    fund_name,\n    SUM(operation_value)\nFROM investments i\nLEFT JOIN funds f ON f.fund_id = i.investment_fund_id\nWHERE investment_owner = ${Investment_Owner:singlequote}\nGROUP BY fund_name;"
    }
   ]
  },
  {
   "title": "Fund Operations",
   "type": "table",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n    OPERATION_QUOTATION_DATE AS \"Date\",\n    FUND_NAME AS \"Fund name\",\n    f.FUND_ID AS \"Fund ID\",\n    operation_value AS \"Money\"\nFROM INVESTMENTS I \nLEFT JOIN FUNDS F ON f.FUND_ID = i.INVESTMENT_FUND_ID\nWHERE investment_owner = ${Investment_Owner:singlequote};"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "PLN" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH results_with_rank AS (\n    SELECT\n        *,\n        ROW_NUMBER () OVER (PARTITION BY fund_id, investment_id ORDER BY result_date DESC) as \"rank\"\n    FROM investment_results\n\n),\n\nfiltered_investment_results AS (\n\tSELECT \n\t\t*\n\tfrom results_with_rank\n\tWHERE  rank = 1\n),\n\nrefund_per_investment AS (\n    SELECT\n        SUM(FUND_VALUE - FUND_INVESTED_MONEY) AS \"Profit\"\n    FROM filtered_investment_results ir\n    INNER JOIN (\n        SELECT DISTINCT \n            investment_id, \n            investment_name  \n        FROM investments i\n        WHERE investment_owner = ${Investment_Owner:singlequote}\n    ) i ON i.investment_id  = ir.investment_id\n)\nSELECT \n    * \nFROM refund_per_investment"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "/*\n    .DESCRIPTION\n        Query for Grafana Dashboard.\n        Display investment results like in table similar to the first console one\n\n\n    .NOTES\n\n        Version:            1.0\n        Author:             Stanisław Horna\n        Mail:               stanislawhorna@outlook.com\n        GitHub Repository:  https://github.com/StanislawHornaGitHub/Investment\n        Creation Date:      28-Mar-2024\n        ChangeLog:\n\n        Date            Who                     What\n        2024-03-29      Stanisław Horna         Changed to CTE to have the proper result,\n                                                if not all funds have new quotations\n*/\n\nWITH results_with_rank AS (\n    SELECT\n        *,\n        ROW_NUMBER () OVER (PARTITION BY fund_id, investment_id ORDER BY result_date DESC) AS \"rank\"\n    FROM investment_results\n\n),\n\nfiltered_investment_results AS (\n\tSELECT \n\t\t*\n\tFROM results_with_rank\n\tWHERE  rank = 1\n),\n\nrefund_per_investment AS (\n    SELECT\n        ir.investment_id,\n        ir.fund_id,\n        FUND_VALUE - FUND_INVESTED_MONEY AS \"Profit\"\n    FROM filtered_investment_results ir\n    GROUP BY ir.investment_id, ir.fund_id, FUND_VALUE, FUND_INVESTED_MONEY\n)\n\n\nSELECT \n\ti.investment_name AS \"Investment name\",\n\tf.fund_id AS \"Fund ID\",\n\tresult_date AS \"Quotation date\",\n\t\"Profit\" AS \"Overall profit\",\n    last_day_result AS \"Last day profit\",\n    last_week_result AS \"Last week profit\",\n    last_month_result AS \"Last month profit\",\n\tlast_day_result / fund_invested_money * 100 AS \"Last day refund\",\n\tlast_week_result / fund_invested_money * 100 AS \"Last week refund\",\n\tlast_month_result / fund_invested_money * 100 AS \"Last month refund\"\nFROM (\nSELECT \n\tinvestment_id,\n\tfund_id,\n\tSUM(\"Profit\") as \"Profit\"\nFROM refund_per_investment\nGROUP BY ROLLUP(investment_id, fund_id)   \n) AS ir\nINNER JOIN (\n    SELECT DISTINCT\n        investment_id,\n        investment_name\n    FROM investments\n    WHERE investment_owner = ${Investment_Owner:singlequote}\n) AS i ON i.investment_id = ir.investment_id \nLEFT JOIN  filtered_investment_results f ON f.fund_id = ir.fund_id AND f.investment_id = ir.investment_id\nWHERE ir.investment_id IS NOT NULL "
    }
   ]
  },
  {
   "title": "Profit over time  (investment wallet)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "PLN" } },
   "targets": [
    {
     "rawSql": "SELECT\n    result_date AS \"time\",\n    i.investment_name  AS \"metric\",\n    SUM(FUND_VALUE - FUND_INVESTED_MONEY) AS \"value\"\nFROM investment_results ir\nINNER JOIN (\n    SELECT DISTINCT \n        investment_id, \n        investment_name  \n    FROM investments i\n    WHERE investment_owner = ${Investment_Owner:singlequote}\n) i ON i.investment_id  = ir.investment_id\nGROUP BY  RESULT_DATE, i.INVESTMENT_NAME;"
    }
   ]
  },
  {
   "title": "Refund over time (investment wallet)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "rawSql": "SELECT \n    result_date AS \"time\",\n    i.investment_name AS \"metric\",\n    SUM((fund_value - fund_invested_money)) /SUM(fund_invested_money) * 100 AS \"value\"\nFROM investment_results ir\nINNER JOIN (\n    SELECT DISTINCT \n        investment_id, \n        investment_name  \n    FROM investments i\n    WHERE i.investment_owner = ${Investment_Owner:singlequote}\n) i ON i.investment_id = ir.investment_id\nWHERE FUND_INVESTED_MONEY <> 0\nGROUP BY result_date, i.investment_name;"
    }
   ]
  },
  {
   "title": "Fund results based on latest investment results",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "rawSql": "WITH selected_owner_investments AS (\n    SELECT\n        investment_id\n    FROM investments\n    WHERE investment_owner = ${Investment_Owner:singlequote}\n)\n\n\nSELECT \n    f.fund_id AS \"Fund ID\",\n    fund_name AS \"Fund Name\",\n    \"Daily refund\",\n    \"Weekly refund\",\n    \"Monthly refund\",\n    CASE \n        WHEN \"Monthly refund\" is not NULL  THEN (\"Monthly refund\"/30) * 365\n        WHEN \"Weekly refund\" is not NULL THEN (\"Weekly refund\"/7) * 365\n        WHEN \"Daily refund\" is not NULL THEN (\"Daily refund\") * 365\n    END AS \"Estimated yearly refund\"\nFROM (\n    SELECT \n        FUND_ID,\n        (last_day_result / fund_invested_money) * 100 AS \"Daily refund\",\n        (last_week_result / fund_invested_money) * 100 AS \"Weekly refund\",\n        (last_month_result / fund_invested_money) * 100 AS \"Monthly refund\"\n    FROM investment_results ir \n    WHERE result_date = (\n        SELECT \n            MAX(result_date) \n        FROM investment_results ir2 \n        WHERE ir2.investment_id = ir.investment_id\n        ) AND investment_id IN (\n                SELECT\n                    investment_id\n                FROM selected_owner_investments\n            )\n) AS s\nLEFT JOIN funds f on f.fund_id = s.fund_id;"
    }
   ]
  },
  {
   "title": "Investment refund %",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "panels": [
    {
     "title": "Refund per day (investment wallet)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 64 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "rawSql": "SELECT\n    result_date AS \"time\",\n    i.investment_name  AS \"metric\",\n    SUM(last_day_result/ fund_invested_money) * 100 AS \"value\"\nFROM investment_results ir\nINNER JOIN (\n    SELECT DISTINCT \n        investment_id, \n        investment_name  \n    FROM investments i\n    WHERE investment_owner = ${Investment_Owner:singlequote}\n) i ON i.investment_id  = ir.investment_id\nGROUP BY result_date, i.investment_name;"
      }
     ]
    },
    {
     "title": "Refund per week (investment wallet)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "rawSql": "SELECT\n    result_date AS \"time\",\n    i.investment_name  AS \"metric\",\n    SUM(last_week_result/ fund_invested_money) * 100 AS \"value\"\nFROM investment_results ir\nINNER JOIN (\n    SELECT DISTINCT \n        investment_id, \n        investment_name  \n    FROM investments i\n    WHERE investment_owner = ${Investment_Owner:singlequote}\n) i ON i.investment_id  = ir.investment_id\nGROUP BY result_date, i.investment_name;"
      }
     ]
    },
    {
     "title": "Refund per month (investment wallet)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "rawSql": "SELECT\n    result_date AS \"time\",\n    i.investment_name  AS \"metric\",\n    SUM(last_month_result/ fund_invested_money) * 100 AS \"value\"\nFROM investment_results ir\nINNER JOIN (\n    SELECT DISTINCT \n        investment_id, \n        investment_name  \n    FROM investments i\n    WHERE investment_owner = ${Investment_Owner:singlequote}\n) i ON i.investment_id  = ir.investment_id\nGROUP BY result_date, i.investment_name;"
      }
     ]
    }
   ]
  },
  {
   "title": "Investment profit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "panels": [
    {
     "title": "Profit per day (investment wallet)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "PLN" } },
     "targets": [
      {
       "rawSql": "SELECT\nresult_date AS \"time\",\ni.investment_name  AS \"metric\",\nSUM(last_day_result) AS \"value\"\nFROM investment_results ir\nINNER JOIN  (\n    SELECT DISTINCT \n        investment_id, \n        investment_name  \n    FROM investments i\n    WHERE investment_owner = ${Investment_Owner:singlequote}\n) i ON i.investment_id  = ir.investment_id\nGROUP BY result_date, i.investment_name;"
      }
     ]
    },
    {
     "title": "Profit per week (investment wallet)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 109 },
     "fieldConfig": { "defaults": { "unit": "PLN" } },
     "targets": [
      {
       "rawSql": "SELECT\n    result_date AS \"time\",\n    i.investment_name  AS \"metric\",\n    SUM(last_week_result) AS \"value\"\nFROM investment_results ir\nINNER JOIN (\n    SELECT DISTINCT \n        investment_id, \n        investment_name  \n    FROM investments i\n    WHERE investment_owner = ${Investment_Owner:singlequote}\n) i ON i.investment_id  = ir.investment_id\nGROUP BY RESULT_DATE, i.INVESTMENT_NAME;"
      }
     ]
    },
    {
     "title": "Profit per month (investment wallet)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 120 },
     "fieldConfig": { "defaults": { "unit": "PLN" } },
     "targets": [
      {
       "rawSql": "SELECT\n    result_date AS \"time\",\n    i.investment_name  AS \"metric\",\n    SUM(last_month_result) AS \"value\"\nFROM investment_results ir\nINNER JOIN (\n    SELECT DISTINCT \n        investment_id, \n        investment_name  \n    FROM investments i\n    WHERE investment_owner = ${Investment_Owner:singlequote}\n) i ON i.investment_id  = ir.investment_id\nGROUP BY result_date, i.investment_name;"
      }
     ]
    }
   ]
  },
  {
   "title": "Funds refund %",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Refund per day (Fund)",
     "type": "timeseries",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "rawSql": "SELECT\n    result_date AS time,\n    fund_name AS metric,\n    (last_day_result / fund_invested_money) * 100 AS value\nFROM investment_results ir \nLEFT JOIN funds f ON f.fund_id = ir.fund_id\nWHERE investment_id IN (\n    SELECT DISTINCT\n        investment_id\n    FROM investments\n    WHERE investment_owner = ${Investment_Owner:singlequote}\n);"
      }
     ]
    },
    {
     "title": "Refund per week (Fund)",
     "type": "timeseries",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 151 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "rawSql": "SELECT\n    result_date AS time,\n    fund_name AS metric,\n    (last_week_result / fund_invested_money) * 100 AS value\nFROM investment_results ir \nLEFT JOIN funds f ON f.fund_id = ir.fund_id\nWHERE investment_id IN (\n    SELECT DISTINCT\n        investment_id\n    FROM investments\n    WHERE investment_owner = ${Investment_Owner:singlequote}\n);"
      }
     ]
    },
    {
     "title": "Refund per month (Fund)",
     "type": "timeseries",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 170 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "rawSql": "SELECT\n    result_date AS time,\n    fund_name AS metric,\n    (last_month_result / fund_invested_money) * 100 AS value\nFROM investment_results ir \nLEFT JOIN funds f ON f.fund_id = ir.fund_id\nWHERE investment_id IN (\n    SELECT DISTINCT\n        investment_id\n    FROM investments\n    WHERE investment_owner = ${Investment_Owner:singlequote}\n);"
      }
     ]
    }
   ]
  },
  {
   "title": "Fund profit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "Profit per day (Fund)",
     "type": "timeseries",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 190 },
     "fieldConfig": { "defaults": { "unit": "PLN" } },
     "targets": [
      {
       "rawSql": "SELECT\n    result_date AS time,\n    fund_name AS metric,\n    last_day_result AS value\nFROM investment_results ir \nLEFT JOIN funds f ON f.fund_id = ir.fund_id\nWHERE investment_id IN (\n    SELECT DISTINCT\n        investment_id\n    FROM investments\n    WHERE investment_owner = ${Investment_Owner:singlequote}\n)"
      }
     ]
    },
    {
     "title": "Profit per week (Fund)",
     "type": "timeseries",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 209 },
     "fieldConfig": { "defaults": { "unit": "PLN" } },
     "targets": [
      {
       "rawSql": "SELECT\n    result_date AS time,\n    fund_name AS metric,\n    last_week_result AS value\nFROM investment_results ir \nLEFT JOIN funds f ON f.fund_id = ir.fund_id\nWHERE investment_id IN (\n    SELECT DISTINCT\n        investment_id\n    FROM investments\n    WHERE investment_owner = ${Investment_Owner:singlequote}\n    )"
      }
     ]
    },
    {
     "title": "Profit per month (Fund)",
     "type": "timeseries",
     "gridPos": { "h": 17, "w": 24, "x": 0, "y": 225 },
     "fieldConfig": { "defaults": { "unit": "PLN" } },
     "targets": [
      {
       "rawSql": "SELECT\n    result_date AS time,\n    fund_name AS metric,\n    last_month_result AS value\nFROM investment_results ir \nLEFT JOIN funds f ON f.fund_id = ir.fund_id\nWHERE investment_id IN (\n    SELECT DISTINCT\n        investment_id\n    FROM investments\n    WHERE investment_owner = ${Investment_Owner:singlequote}\n    )"
      }
     ]
    }
   ]
  }
 ]
}