{
 "title": "Investment Management",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Backend_IP", "label": "Backend Address", "query": "API" },
   { "name": "Backend_Port", "label": "Backend Port", "query": "5000" }
  ]
 },
 "panels": [
  {
   "title": "Resource consumption",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\tcpu.\"CPU normal\",\n\tcpu.\"CPU niced\",\n\tcpu.\"CPU kernel\",\n\tram.\"RAM usage\"\nFROM\n\t(\n\t\tSELECT\n\t\t\tROUND(\n\t\t\t\t(USED_MEMORY::NUMERIC / TOTAL_MEMORY::NUMERIC) * 100,\n\t\t\t\t2\n\t\t\t) AS \"RAM usage\"\n\t\tFROM\n\t\t\tPG_SYS_MEMORY_INFO ()\n\t) AS ram,\n\t(\n\t\tSELECT\n\t\t\tROUND(USERMODE_NORMAL_PROCESS_PERCENT::NUMERIC, 2) AS \"CPU normal\",\n\t\t\tROUND(USERMODE_NICED_PROCESS_PERCENT::NUMERIC, 2) AS \"CPU niced\",\n\t\t\tROUND(KERNELMODE_PROCESS_PERCENT::NUMERIC, 2) AS \"CPU kernel\"\n\t\tFROM\n\t\t\tPG_SYS_CPU_USAGE_INFO ()\n\t) AS cpu;\n\n\n\n"
    }
   ]
  },
  { "title": "Control buttons", "type": "speakyourcode-button-panel", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Fund Quotation Dates",
   "type": "table",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "WITH funds_quotation_with_rank AS (\n    SELECT\n        *,\n        ROW_NUMBER () OVER (PARTITION BY fund_id ORDER BY date DESC) AS \"rank\"\n    FROM quotations q\n)\n\nSELECT \n    date AS \"Date\",\n    f.fund_id AS \"Fund ID\",\n    fund_name AS \"Fund name\"\nFROM funds_quotation_with_rank fq\nLEFT JOIN funds f ON f.FUND_ID = fq.fund_id\nWHERE rank = 1"
    }
   ]
  },
  {
   "title": "Fund quotation refresh ratio",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 5, "x": 7, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH refreshed_funds AS (\n    SELECT \n        COUNT(*) AS \"Refreshed\"\n    FROM quotations\n    WHERE date = (\n        SELECT \n            MAX(date)\n        FROM quotations \n    )\n),\n\nall_funds AS (\n    SELECT\n        COUNT(*) AS \"All funds\"\n    FROM funds\n)\n\nSELECT\n    \"Refreshed\",\n    (\"All funds\" - \"Refreshed\") AS \"Not refreshed\"\nFROM refreshed_funds, all_funds\n"
    }
   ]
  },
  {
   "title": "Investment Result Dates",
   "type": "table",
   "gridPos": { "h": 13, "w": 7, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "WITH investment_results_with_rank AS (\n    SELECT\n        *,\n        ROW_NUMBER () OVER (PARTITION BY fund_id, investment_id ORDER BY result_date DESC) AS \"rank\"\n    FROM investment_results ir\n)\n\nSELECT \n    result_date AS \"Date\",\n    investment_name AS \"Investment name\",\n    investment_owner AS \"Owner\"\nFROM (\n        SELECT \n            investment_id,\n            MIN(result_date) as \"result_date\"\n        FROM investment_results_with_rank\n        WHERE rank = 1\n        GROUP BY investment_id\n) AS r\nLEFT JOIN (\n        SELECT DISTINCT \n            investment_id, \n            investment_name,\n            investment_owner\n        FROM investments i\n) AS i ON i.investment_id = r.investment_id"
    }
   ]
  },
  {
   "title": "Investment results refresh ratio",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 5, "x": 19, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH last_investment_date AS (\n    SELECT \n        MAX(result_date) as \"last_result_date\"\n    FROM investment_results\n),\n\nrefreshed_investments AS (\n    SELECT\n        COUNT(*) AS \"Refreshed\"\n    FROM (\n        SELECT DISTINCT\n            investment_id\n        FROM investment_results\n        WHERE result_date = (\n            SELECT \n                last_result_date\n            FROM last_investment_date\n        )\n    ) AS i\n    WHERE\n        ( -- Get number of funds in investment with ID from outer query\n            SELECT \n                COUNT(*)\n            FROM (\n                SELECT DISTINCT \n                    investment_fund_id \n                FROM investments\n                WHERE \n                    investment_id = i.investment_id \n            )\n        ) = ( -- Get number of results for current day in investment with ID from outer query\n            SELECT\n                COUNT(*)\n            FROM (\n                SELECT\n                    fund_id\n                FROM investment_results\n                WHERE \n                    investment_id = i.investment_id AND\n                    result_date = (\n                        SELECT \n                            last_result_date\n                        FROM last_investment_date\n                    )\n            )\n        )\n),\n\nall_investments AS (\n    SELECT\n        COUNT(*) AS \"All investments\"\n    FROM (\n        SELECT DISTINCT\n            investment_id\n        FROM investments\n    )\n)\n\nSELECT\n    \"Refreshed\",\n    (\"All investments\" - \"Refreshed\") AS \"Not refreshed\"\nFROM refreshed_investments, all_investments\n\n"
    }
   ]
  }
 ]
}